#!/usr/bin/env python3
"""Mirror the canonical skill into the generated discovery copies.

``skills/architecturehell/`` is the single source of truth. The discovery
copies at ``.claude/skills/architecturehell/`` and
``.agents/skills/architecturehell/`` exist so a cloned repository is
auto-discovered by Claude Code and Codex; they are generated by this script
from a fixed file manifest and must never be edited by hand. Files found in
a discovery copy that are not in the manifest are removed. The repository
LICENSE is copied into every skill copy so installed skills carry it.

Usage:
  python tools/sync_skills.py          # regenerate the discovery copies
  python tools/sync_skills.py --check  # verify only; exit 1 on any drift
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILL = "architecturehell"
CANONICAL = Path("skills") / SKILL
COPIES = (
    Path(".claude") / "skills" / SKILL,
    Path(".agents") / "skills" / SKILL,
)
# Fixed manifest: never sweep a worktree. Add new skill files here explicitly.
FILES = (
    "SKILL.md",
    "LICENSE",
    "agents/openai.yaml",
    "assets/reference-style.jpeg",
    "references/critique-lenses.md",
    "references/manifest-schema.md",
    "references/roast-level.md",
    "references/voice-and-copy.md",
    "scripts/annotate_architecture.py",
)


def files_differ(a: Path, b: Path) -> bool:
    return not b.is_file() or a.read_bytes() != b.read_bytes()


def sync(root: Path, check: bool = False) -> list[str]:
    """Synchronize (or, with check=True, audit) the discovery copies.

    Returns a list of problems found in check mode; empty means in sync.
    Raises SystemExit for a broken canonical layout in either mode.
    """
    problems: list[str] = []
    canonical = root / CANONICAL
    license_src = root / "LICENSE"
    if not license_src.is_file():
        raise SystemExit("missing LICENSE at the repository root")

    canonical_license = canonical / "LICENSE"
    if check:
        if files_differ(license_src, canonical_license):
            problems.append(f"out of sync: {CANONICAL / 'LICENSE'}")
    else:
        shutil.copy2(license_src, canonical_license)

    for name in FILES:
        if not (canonical / name).is_file():
            raise SystemExit(f"missing required canonical file: {CANONICAL / name}")

    for copy_rel in COPIES:
        copy_root = root / copy_rel
        for name in FILES:
            src = canonical / name
            dst = copy_root / name
            if check:
                if files_differ(src, dst):
                    problems.append(f"out of sync: {copy_rel / name}")
            else:
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
        if not copy_root.exists():
            continue
        manifest_paths = {(copy_root / name).resolve() for name in FILES}
        for path in sorted(copy_root.rglob("*")):
            if path.is_file() and path.resolve() not in manifest_paths:
                if check:
                    problems.append(f"stray file: {path.relative_to(root)}")
                else:
                    path.unlink()
                    print(f"removed stray file: {path.relative_to(root)}")
        if not check:
            for directory in sorted(
                (p for p in copy_root.rglob("*") if p.is_dir()), reverse=True
            ):
                if not any(directory.iterdir()):
                    directory.rmdir()
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate or verify the generated skill discovery copies."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify without writing; exit 1 if anything is out of sync",
    )
    args = parser.parse_args(argv)
    problems = sync(ROOT, check=args.check)
    if args.check:
        if problems:
            for problem in problems:
                print(problem, file=sys.stderr)
            print(
                "discovery copies have drifted; run: python tools/sync_skills.py",
                file=sys.stderr,
            )
            return 1
        print("skill discovery copies are in sync")
        return 0
    print(f"synced {len(FILES)} files into {len(COPIES)} discovery copies")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
